M48
; DRILL file {KiCad (5.99.0-10388-g9b1890606d)} date Sat May  8 21:35:34 2021
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2021-05-08T21:35:34-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(5.99.0-10388-g9b1890606d)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1575
%
G90
G05
T1
X5.0Y-1.85
X5.0Y-5.45
X7.2Y-1.85
X7.2Y-5.45
T2
X7.0075Y-3.2524
T0
M30
